name: build suite
on: [pull_request]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build job
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - uses: actions/checkout@v2
      - name: Run tests
        run: npm install && npm run build
